{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nodeharvest.serviceAccountName" . }}
  labels:
    {{- include "nodeharvest.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
